#ifndef EXPR_OPERATIONS_H
#define EXPR_OPERATIONS_H
#include "operations/add.h"
#include "operations/boolean.h"
#include "operations/divide.h"
#include "operations/modulo.h"
#include "operations/multiply.h"
#include "operations/pow.h"
#include "operations/subtract.h"
#endif //EXPR_OPERATIONS_H
